# Site settings
title: tlkuo's blog
email: tlkuo.frb@gmail.com
description: the blog is stuffed bits and pieces of tlkuo's life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tlkuo.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# Reference http://jekyllrb.com/docs/assets/#sassscss
sass:
  style: compressed

# GitHub Pages settings (can not change)
# Reference https://help.github.com/articles/using-jekyll-with-pages/#configuration-overrides
safe: true
lsi: false
source: .

# Reference http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title/

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
