# Site settings
title: tlkuo's blog
email: tlkuo.frb@gmail.com
website: tlkuo.frb.tw
description: the blog is stuffed bits and pieces of tlkuo's life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tlkuo.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# GitHub Pages settings (can not change)
safe: true
lsi: false
source: .
